"""empty message

Revision ID: eee8aa83a324
Revises: 0c3a9428d85a
Create Date: 2022-03-28 00:59:25.706404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eee8aa83a324'
down_revision = '0c3a9428d85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('plate', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('plate', 'start_time')
    op.drop_column('plate', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('plate', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('plate', 'end_date')
    op.drop_column('plate', 'start_date')
    # ### end Alembic commands ###
